config/routes.rb
Rails.application.routes.draw do
  resources :hero1s

  resources :heros

  resources :users

  root 'users#index'

  get 'index' => 'users#index'
  get 'display_page' => 'users#display_page'
  get 'pay_schedule' => 'users#pay_schedule'
  get 'display_page_in_hero' => 'heros#display_page_in_hero'
  get 'new_edit' => 'heros#new_edit'
  post 'new_edit' => 'heros#new_edit'
  get 'fullyear' => 'users#fullyear'
  get 'march' => 'users#march'
  get 'april' => 'users#april'
  get 'may' => 'users#may'
  get 'june' => 'users#june'
  get 'july' => 'users#july'
  get 'august' => 'users#august'
  get 'september' => 'users#september'
  get 'october' => 'users#october'
  get 'november' => 'users#november'
  get 'december' => 'users#december'

end

app/models/hero.rb
class Hero < ActiveRecord::Base
  belongs_to :User
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
	@users = User.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
	@heros = Hero.all
  end
  
  def new_edit
	@hero = "Matte"
  end
  
  ####================================================#######
  def display_page_in_hero
	#@userid = params[:hero][:User_id].reject(&:blank?) unless params[:hero].nil?
	#@userid = id
	hash = Hash.new
	hash = {"Sherry" => 1, "Boris" =>2, "Vicente" => 3, "Matte" => 4, "Kevin" => 5, "Zoe" => 6, "Jay" =>7, "Eadon" => 8, 
				"Franky" => 9, "Luis" =>10, "James" => 11, "Jack" => 12}
	 # hash.each do |key, value|
	 # if key == @user.name
		# @uservalue = value
	 # end
	 # end
  end
  
  
####===================================================#######
  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero}
        format.json { render :show, status: :ok, location: @hero }
       else
         format.html { render :edit }
         format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:day, :User_id)
    end
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/heros/_form.html.erb
<%= form_for @hero do |f| %>
 
  <div class="field">
    <%= f.label :day %><br>
    <%= f.date_select :day %>
  </div>
  <div class#="field">
    <%#= f.label :User_id %><br>
    <%#= f.text_field :User_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/heros/display_page_in_hero.html.erb
<h1>Days on which you are Super Hero</h1>
<%= :id %>
<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% Hero.where(:user_id => :User_id).each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
        <td><%= link_to 'Swap', edit_hero_path(hero) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/heros/edit.html.erb
<h1>Editing Support Hero Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back to Home Page', users_path %>

<h3> Use the information below to select a swap date </h3>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/heros/index.html.erb
<h1>Select "Swap with" for the user who is a support hero on the date you swapped to</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
        <td><%= link_to 'Swap with', edit_hero_path(hero) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to Home Page', users_path %>

app/views/heros/new.html.erb
<h1>New hero</h1>

<%= render 'form' %>

<%= link_to 'Back', heros_path %>

app/views/heros/new_edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/heros/show.html.erb
<h3> If you have already selected the person to swap with, click on "New Schedule" to view New Schedule<br> Else, click on "Swap with" </br> </h3>

<p id="notice"><%= notice %></p>

<p>
  <strong>Day you swapped to:</strong>
  <%= @hero.day %>
</p>

<p>
  <strong>User:</strong>
  <%= @hero.User.name %>
</p>




<%= link_to 'Re- select date', edit_hero_path(@hero) %> 
<%= link_to 'Swap with', heros_path %>
<%= link_to 'New Schedule', pay_schedule_path %>