config/routes.rb
Rails.application.routes.draw do
  resources :hero1s

  resources :heros

  resources :users

  root 'users#index'

  get 'index' => 'users#index'
  get 'display_page' => 'users#display_page'
  get 'pay_schedule' => 'users#pay_schedule'
  get 'display_page_in_hero' => 'heros#display_page_in_hero'
  get 'new_edit' => 'heros#new_edit'
  post 'new_edit' => 'heros#new_edit'
  get 'fullyear' => 'users#fullyear'
  get 'march' => 'users#march'
  get 'april' => 'users#april'
  get 'may' => 'users#may'
  get 'june' => 'users#june'
  get 'july' => 'users#july'
  get 'august' => 'users#august'
  get 'september' => 'users#september'
  get 'october' => 'users#october'
  get 'november' => 'users#november'
  get 'december' => 'users#december'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
	vall = params[:user][:name].reject(&:blank?) unless params[:user].nil?
	@user = User.new(name: vall)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
  
  ####================================================#######
  def display_page
	@user = User.new(name: params[:user][:name])
	hash = Hash.new
	hash = {"Sherry" => 1, "Boris" =>2, "Vicente" => 3, "Matte" => 4, "Jack" => 5,  "Kevin" =>6, "Zoe" => 7, "Jay" => 8,
				"Eadon" => 9, "Franky" => 10,  "Luis" => 11, "James" => 12}
	 hash.each do |key, value|
	 if key == @user.name
		@uservalue = value
	 end
	 end
  end
  
  def pay_schedule
	 @heros = Hero.where("day >= '2016-02-01' AND day <= '2016-02-29'")
  end
  
  def march
	@heros = Hero.where("day >= '2016-03-01' AND day <= '2016-03-31'")
  end
  def april
	@heros = Hero.where("day >= '2016-04-01' AND day <= '2016-04-30'")
  end
  def may
	@heros = Hero.where("day >= '2016-05-01' AND day <= '2016-05-31'")
  end
  def june
	@heros = Hero.where("day >= '2016-06-01' AND day <= '2016-06-30'")
  end
  def july
	@heros = Hero.where("day >= '2016-07-01' AND day <= '2016-07-31'")
  end
  def august
	@heros = Hero.where("day >= '2016-08-01' AND day <= '2016-08-31'")
  end
  def september
	@heros = Hero.where("day >= '2016-09-01' AND day <= '2016-09-30'")
  end
  def october
	@heros = Hero.where("day >= '2016-10-01' AND day <= '2016-10-31'")
  end
  def november
	@heros = Hero.where("day >= '2016-11-01' AND day <= '2016-11-30'")
  end
  def december
	@heros = Hero.where("day >= '2016-12-01' AND day <= '2016-12-31'")
  end
  ######===============================================######

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/august.html.erb
<style> 
	body {
			background-image: url("1.jpg");
			background-repeat: no-repeat;
			background-position: center right; 
			background-size: 400px 350px;
		 }
</style>

<h2> August 2016 Schedule for all the Employees </h2>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3> Note: On the days you are not Support Hero, you are Report Hero (implies your presence is needed ":)") </h3>
<%= link_to 'February 2016', pay_schedule_path %>
<%= link_to 'March 2016', march_path %> 
<%= link_to 'April 2016', april_path %>
<%= link_to 'May 2016', may_path %> 
<%= link_to 'June 2016', june_path %> 
<%= link_to 'July 2016', july_path %>  
<%= link_to 'September 2016', september_path %>
<%= link_to 'October 2016', october_path %> 
<%= link_to 'November 2016', november_path %> 
<%= link_to 'December 2016', december_path %> <br> 
<%= link_to 'Back to Home Page', users_path %>

app/views/users/december.html.erb
<style> 
	body {
			background-image: url("1.jpg");
			background-repeat: no-repeat;
			background-position: center right; 
			background-size: 400px 350px;
		 }
</style>

<h2> December 2016 Schedule for all the Employees </h2>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3> Note: On the days you are not Support Hero, you are Report Hero (implies your presence is needed ":)") </h3>
<%= link_to 'February 2016', pay_schedule_path %>
<%= link_to 'March 2016', march_path %> 
<%= link_to 'April 2016', april_path %>
<%= link_to 'May 2016', may_path %> 
<%= link_to 'June 2016', june_path %> 
<%= link_to 'July 2016', july_path %> 
<%= link_to 'August 2016', august_path %> 
<%= link_to 'September 2016', september_path %>
<%= link_to 'October 2016', october_path %> 
<%= link_to 'November 2016', november_path %>  <br> 
<%= link_to 'Back to Home Page', users_path %>

app/views/users/display_page.html.erb
<h1>Days on which you are Super Hero</h1>
<%#= @uservalue %>
<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% Hero.where('User' => @uservalue).each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
        <td><%= link_to 'Swap', edit_hero_path(hero) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/fullyear.html.erb
<style> 
	body {
			background-image: url("1.jpg");
			background-repeat: no-repeat;
			background-position: center right; 
			background-size: 400px 350px;
		 }
</style>

<h2> Click on the required month below </h2> <br> <br>
<%= link_to 'February 2016', pay_schedule_path %> <br>
<%= link_to 'March 2016', march_path %> <br>
<%= link_to 'April 2016', april_path %>  <br>
<%= link_to 'May 2016', may_path %> <br>
<%= link_to 'June 2016', june_path %> <br>
<%= link_to 'July 2016', july_path %> <br>
<%= link_to 'August 2016', august_path %> <br>
<%= link_to 'September 2016', september_path %> <br>
<%= link_to 'October 2016', october_path %> <br>
<%= link_to 'November 2016', november_path %> <br>
<%= link_to 'December 2016', december_path %> <br> <br> <br> <br> <br>
<%= link_to 'Back to Home Page', users_path %>

app/views/users/index.html.erb
<style> 
	body {
			background-image: url("1.jpg");
			background-repeat: no-repeat;
			background-position: center right; 
			background-size: 400px 350px;
		 }
</style>

<h1>Welcome!</h1> <br><br>
<h2> Today's Date:  <%= Date.today %></h2>
<h2> Today's Super Hero: <% Hero.where(:day => Date.today).each do |hero| %>
							<%= hero.User.name %> <% end %></h2>

<br><br>

<h3> Our Heroes Family: <br> Sherry, Boris, Vicente, Matte, Kevin, Zoe, Jay, Eadon, 
				Franky, James, Luis, Jack </h3><br>

<h3> Enter your Name in below to view your schedule </h3>
<%= form_for @user, :url => {:action => "display_page", :name => :name}, :html => {:method => :get} do |f| %>
<%= f.label :first_name %><br />
    <%= f.text_field :name, :placeholder => "I'm Case Sensitive" %><br />  <br>      
  <%= f.submit "View My Schedule" %>
<% end %>
<br><br><br><br><br>
<%= link_to '2016 Full Schedule', fullyear_path %>

app/views/users/june.html.erb
<style> 
	body {
			background-image: url("1.jpg");
			background-repeat: no-repeat;
			background-position: center right; 
			background-size: 400px 350px;
		 }
</style>

<h2> June 2016 Schedule for all the Employees </h2>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3> Note: On the days you are not Support Hero, you are Report Hero (implies your presence is needed ":)") </h3>
<%= link_to 'February 2016', pay_schedule_path %>
<%= link_to 'March 2016', march_path %> 
<%= link_to 'April 2016', april_path %>
<%= link_to 'May 2016', may_path %>  
<%= link_to 'July 2016', july_path %> 
<%= link_to 'August 2016', august_path %> 
<%= link_to 'September 2016', september_path %>
<%= link_to 'October 2016', october_path %> 
<%= link_to 'November 2016', november_path %> 
<%= link_to 'December 2016', december_path %> <br> 
<%= link_to 'Back to Home Page', users_path %>

app/views/users/may.html.erb
<style> 
	body {
			background-image: url("1.jpg");
			background-repeat: no-repeat;
			background-position: center right; 
			background-size: 400px 350px;
		 }
</style>

<h2> May 2016 Schedule for all the Employees </h2>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3> Note: On the days you are not Support Hero, you are Report Hero (implies your presence is needed ":)") </h3>
<%= link_to 'February 2016', pay_schedule_path %>
<%= link_to 'March 2016', march_path %> 
<%= link_to 'April 2016', april_path %>
<%= link_to 'June 2016', june_path %> 
<%= link_to 'July 2016', july_path %> 
<%= link_to 'August 2016', august_path %> 
<%= link_to 'September 2016', september_path %>
<%= link_to 'October 2016', october_path %> 
<%= link_to 'November 2016', november_path %> 
<%= link_to 'December 2016', december_path %> <br> 
<%= link_to 'Back to Home Page', users_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/november.html.erb
<style> 
	body {
			background-image: url("1.jpg");
			background-repeat: no-repeat;
			background-position: center right; 
			background-size: 400px 350px;
		 }
</style>

<h2> November 2016 Schedule for all the Employees </h2>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3> Note: On the days you are not Support Hero, you are Report Hero (implies your presence is needed ":)") </h3>
<%= link_to 'February 2016', pay_schedule_path %>
<%= link_to 'March 2016', march_path %> 
<%= link_to 'April 2016', april_path %>
<%= link_to 'May 2016', may_path %> 
<%= link_to 'June 2016', june_path %> 
<%= link_to 'July 2016', july_path %> 
<%= link_to 'August 2016', august_path %> 
<%= link_to 'September 2016', september_path %>
<%= link_to 'October 2016', october_path %> 
<%= link_to 'December 2016', december_path %> <br> 
<%= link_to 'Back to Home Page', users_path %>

app/views/users/october.html.erb
<style> 
	body {
			background-image: url("1.jpg");
			background-repeat: no-repeat;
			background-position: center right; 
			background-size: 400px 350px;
		 }
</style>

<h2> October 2016 Schedule for all the Employees </h2>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3> Note: On the days you are not Support Hero, you are Report Hero (implies your presence is needed ":)") </h3>
<%= link_to 'February 2016', pay_schedule_path %>
<%= link_to 'March 2016', march_path %> 
<%= link_to 'April 2016', april_path %>
<%= link_to 'May 2016', may_path %> 
<%= link_to 'June 2016', june_path %> 
<%= link_to 'July 2016', july_path %> 
<%= link_to 'August 2016', august_path %> 
<%= link_to 'September 2016', september_path %>
<%= link_to 'November 2016', november_path %> 
<%= link_to 'December 2016', december_path %> <br> 
<%= link_to 'Back to Home Page', users_path %>

app/views/users/pay_schedule.html.erb
<style> 
	body {
			background-image: url("1.jpg");
			background-repeat: no-repeat;
			background-position: center right; 
			background-size: 400px 350px;
		 }
</style>

<h2> <%= Date.today.strftime("%Y - %m") %> month's Schedule for all the Employees </h2>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% Hero.order('day').first(16).each do |hero| %>
      <tr>
        <td><%= hero.day %></td>
        <td><%= hero.User.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3> Note: On the days you are not Support Hero, you are Report Hero (implies your presence is needed ":)") </h3>

<%= link_to 'Back to Home Page', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>